### ISSUE TITLE
#F002#001: 게시글 작성 시간대 오류 발생.

### ISSUE THREAD

**Issue by WachsenHaus** [WachsenHaus/acorn_ateam#37]
![image](https://user-images.githubusercontent.com/59411545/88999583-e9f08880-d32f-11ea-8e25-8227ff9970c4.png)

sysdate로 시간대를 확인해보면 오라클 DB서버에서는 시간대가 일치하는데

글 작성시에 시간이 틀어짐. 확인 부탁 함

**Comment by parkjye** [comment]
BoardDao의 sql문에서 시간 표기 방법에 오류가 있었음. 
mm -> mi로 수정 완료.

![image](https://user-images.githubusercontent.com/64972932/89154204-65a53c00-d5a1-11ea-8a46-c4ecaa2646b9.png)
